django_vuejs/apps/rest_api/urls.py
from django.conf.urls import url, include
from tastypie.api import Api
from django_vuejs.apps.rest_api.v1 import *

v1_api = Api(api_name='v1')
v1_api.register(LibraryResource())
v1_api.register(AuthorResource())
v1_api.register(BookResource())
v1_api.register(UserResource())

urlpatterns = [
    url(r'^api/', include(v1_api.urls)),
]

django_vuejs/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView

from django_vuejs.apps.rest_api import urls as api_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'', include(api_urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

django_vuejs/apps/book/models.py
from django.db import models


class Library(models.Model):

    name = models.CharField(max_length=100)


class Book(models.Model):

    title = models.CharField(max_length=100)
    author = models.ForeignKey('book.Author', on_delete=models.CASCADE)
    libraries = models.ManyToManyField('book.Library')


class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

django_vuejs/apps/rest_api/models.py
from django.db import models

# Create your models here.

django_vuejs/apps/rest_api/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=50)

django_vuejs/apps/book/views.py
from django.views.generic import ListView

from .models import Book, Author, Library


class BookListView(ListView):
    paginate_by = 100
    model = Book
    context_object_name = 'books'

    def get_queryset(self):
        qs = super(BookListView, self).get_queryset()
        qs.order_by('title')
        return qs


class AuthorListView(ListView):
    paginate_by = 100
    model = Author
    context_object_name = 'authors'


class LibraryListView(ListView):
    paginate_by = 10
    model = Library
    context_object_name = 'libraries'


book_list_view = BookListView.as_view()
author_list_view = AuthorListView.as_view()
library_list_view = LibraryListView.as_view()

django_vuejs/apps/rest_api/views.py
from django.shortcuts import render

# Create your views here.

django_vuejs/apps/book/templates/book/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
</head>
<body>
    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
    <table border="1">
      <tr>
        <th>Author Name</th>
        <th>Number of Books</th>
      </tr>
      {% for author in authors %}
      <tr>
        <td>{{ author.first_name }} {{ author.last_name }}</td>
        <td>{{ author.book_set.count }}</td>
      </tr>
      {% endfor %}
    </table>
</body>
</html>

django_vuejs/apps/book/templates/book/book_list.html
{% load tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
</head>
<body>
    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
    <table border="1">
      <thead>
        <tr>
          <th>Book Title</th>
          <th>Author</th>
          <th>Libraries</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td>{{ book.title }}</td>
          <td>{{ book.author.first_name }} {{ book.author.last_name }}</td>
          <td>{{ book.libraries.all|libraries_name }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
</body>
</html>

django_vuejs/apps/book/templates/book/library_list.html
{% load tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
</head>
<body>
    {% if is_paginated %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
    <table border="1">
      <tr>
        <th>Library</th>
        <th>Books in library</th>
        <th>Different author quantity</th>
      </tr>
      {% for library in libraries %}
      <tr>
        <td>{{ library.name }}</td>
        <td>{{ library.book_set.count }}</td>
        <td>{{ library|author_count }}</td>
      </tr>
      {% endfor %}
    </table>
</body>
</html>